### PR TITLE
Make role MacOS compatible

### PR DESCRIPTION
**Pull request by NileshGule**
Modified the tasks main.yml file. The role is now compatible with MacOSX. 
There are no changes required in the roles configuration. Based on the underlying operating system where the playbook is running the appropriate task file will be executed.

### CODE REVIEW

**Comment by NileshGule** [comment]
updated docker dependency from docker-engine to docker-ce

**Comment by NileshGule** [comment]
Added test to check that installed extension is listed using --list-extensions command

**Comment by freemanjp** [comment]
@NileshGule, thanks for the pull request and sorry for the delay (current work commitments only allow me to update the Ansible roles at weekends). If you sign the Contributor License Agreement I'll merge your change.

**Comment by NileshGule** [comment]
Hi John,
No problem. This is my first contribution to any open source project. I was not aware of the prerequisite to sign the agreement. I'll do it at the earliest.

**Comment by freemanjp** [comment]
@NileshGule, thanks for making this your first opensource contribution. Your change has been merged and is in the new 1.1.0 release of this role.

The change you made was similar to the fix for SUSE Linux support, so it did a little refactoring and made the change work for both (to some extent SUSE will be a surrogate test for MacOS); hopefully I didn't break MacOS support in the process.

**Pull request merged**
